### ISSUE TITLE
console.log not supported on IE9 and earlier

### ISSUE THREAD

**Issue by johnnyshields** [rwjblue/ember-git-version#5]
This line:

```
console.log(config.currentRevision);
```

breaks browsers which do not have a console (IE9 and earlier). Maybe best to remove this entirely.

**Comment by rwjblue** [comment]
We can use `Ember.Logger.info` instead. Would you mind sending a PR?

**Comment by pangratz** [comment]
I think since #6 has been merged, this issue is not relevant anymore: the current revision is not logged anymore inside an initializer...

**Comment by rwjblue** [comment]
Confirm, thank you @pangratz!
