### ISSUE TITLE
Deprecation warning under Ember-CLI 2.12

### ISSUE THREAD

**Issue by jrr** [rwjblue/ember-git-version#9]
```DEPRECATION: Addon files were detected in `/path/to/project/node_modules/ember-git-version/addon`, but no JavaScript preprocessors were found for `ember-git-version`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-git-version`'s `package.json`.```

**Comment by rwjblue** [comment]
Hmm.  This is pretty odd. ember-git-version doesn't have files in `addon/**/*`, so there must be something wrong with the detection that the warning is doing.

**Comment by jfelchner** [comment]
@rwjblue the fact that the `.gitkeep` file is somehow getting in there?

**Comment by jfelchner** [comment]
@rwjblue FWIW I can confirm that removing the `addon/.gitkeep` file silences this warning.

**Comment by rwjblue** [comment]
Would you mind submitting a PR to remove that file?

**Comment by jfelchner** [comment]
@rwjblue definitely would but removing that file would remove the dir from the repo and when the sir is removed it throws an error instead of a warning 🙄

Happy to help with a quick PR if you have thoughts.
